import localFont from "next/font/local";

import StyledComponentsRegistry from "@/lib/registry";
import GlobalStyles from "@/common/GlobalStyles";
import ReduxProvider from "@/common/ReduxProvider";
import "bootstrap/dist/css/bootstrap.min.css";

import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const integralFc = localFont({
  src: [
    {
      path: "../assets/fonts/Fontspring-DEMO-integralcf-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-integralFc",
});

const satoshi = localFont({
  src: [
    {
      path: "../assets/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${integralFc.variable} ${satoshi.variable}`}>
        <ReduxProvider>
          <StyledComponentsRegistry>
            <GlobalStyles />
            <Header />
            <Navbar />
            {children}
          </StyledComponentsRegistry>
        </ReduxProvider>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossOrigin="anonymous"
          async
        ></script>
      </body>
    </html>
  );
}
