import localFont from "next/font/local";

import StyledComponentsRegistry from "@/lib/registry";
import GlobalStyles from "@/common/GlobalStyles";
import ReduxProvider from "@/common/ReduxProvider";
import "bootstrap/dist/css/bootstrap.min.css";

import Navbar from "@/components/Navbar";

const integralFc = localFont({
  src: [
    {
      path: "../../public/fonts/Fontspring-DEMO-integralcf-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-integralFc",
});

const satoshi = localFont({
  src: [
    {
      path: "../../public/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${integralFc.variable} ${satoshi.variable}`}>
        <ReduxProvider>
          <StyledComponentsRegistry>
            <GlobalStyles />
            <Navbar />
            {children}
          </StyledComponentsRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
